export default function BackgroundGradient(props) {
  return (
    <svg
      width={1280}
      height={895}
      viewBox="0 0 1280 895"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g style={{ mixBlendMode: "multiply" }} filter="url(#filter0_f_1391_70)">
        <ellipse
          cx={461}
          cy="376.5"
          rx={304}
          ry="256.5"
          fill="#001AFF"
          fillOpacity="0.12"
        />
      </g>
      <g style={{ mixBlendMode: "multiply" }} filter="url(#filter1_f_1391_70)">
        <ellipse
          cx={414}
          cy="493.5"
          rx={304}
          ry="256.5"
          fill="#FF7A00"
          fillOpacity="0.12"
        />
      </g>
      <g style={{ mixBlendMode: "multiply" }} filter="url(#filter2_f_1391_70)">
        <ellipse
          cx={888}
          cy="389.5"
          rx={304}
          ry="256.5"
          fill="#FF7A00"
          fillOpacity="0.12"
        />
      </g>
      <g style={{ mixBlendMode: "multiply" }} filter="url(#filter3_f_1391_70)">
        <ellipse
          cx={976}
          cy="518.5"
          rx={304}
          ry="256.5"
          fill="#001AFF"
          fillOpacity="0.12"
        />
      </g>
      <defs>
        <filter
          id="filter0_f_1391_70"
          x={37}
          y={0}
          width={848}
          height={753}
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity={0} result="BackgroundImageFix" />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation={60}
            result="effect1_foregroundBlur_1391_70"
          />
        </filter>
        <filter
          id="filter1_f_1391_70"
          x={-10}
          y={117}
          width={848}
          height={753}
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity={0} result="BackgroundImageFix" />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation={60}
            result="effect1_foregroundBlur_1391_70"
          />
        </filter>
        <filter
          id="filter2_f_1391_70"
          x={464}
          y={13}
          width={848}
          height={753}
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity={0} result="BackgroundImageFix" />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation={60}
            result="effect1_foregroundBlur_1391_70"
          />
        </filter>
        <filter
          id="filter3_f_1391_70"
          x={552}
          y={142}
          width={848}
          height={753}
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity={0} result="BackgroundImageFix" />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation={60}
            result="effect1_foregroundBlur_1391_70"
          />
        </filter>
      </defs>
    </svg>
  );
}
